package com.mybatisex.myblog.domain;

public class ManageUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user_info.id
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user_info.user_name
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user_info.user_pw
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    private String userPw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user_info.id
     *
     * @return the value of manage_user_info.id
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user_info.id
     *
     * @param id the value for manage_user_info.id
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user_info.user_name
     *
     * @return the value of manage_user_info.user_name
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user_info.user_name
     *
     * @param userName the value for manage_user_info.user_name
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user_info.user_pw
     *
     * @return the value of manage_user_info.user_pw
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    public String getUserPw() {
        return userPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user_info.user_pw
     *
     * @param userPw the value for manage_user_info.user_pw
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    public void setUserPw(String userPw) {
        this.userPw = userPw;
    }
}