package com.mybatisex.myblog.mapper;

import com.mybatisex.myblog.domain.ManageUserInfo;
import com.mybatisex.myblog.domain.ManageUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManageUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_info
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    int countByExample(ManageUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_info
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    int deleteByExample(ManageUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_info
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_info
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    int insert(ManageUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_info
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    int insertSelective(ManageUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_info
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    List<ManageUserInfo> selectByExample(ManageUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_info
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    ManageUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_info
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") ManageUserInfo record, @Param("example") ManageUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_info
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    int updateByExample(@Param("record") ManageUserInfo record, @Param("example") ManageUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_info
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    int updateByPrimaryKeySelective(ManageUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_info
     *
     * @mbggenerated Sat May 19 18:03:27 CST 2018
     */
    int updateByPrimaryKey(ManageUserInfo record);
}